### PR TITLE
first pass at the linting workflow

### PR DESCRIPTION
**Pull request by yamori**

### CODE REVIEW

**Comment by yamori** [comment]
@zerske , take a look at the added workflows file.  it's basically "any time there's a PR towards main, checkout the code, build the code (or try to find cached dependencies), and run `npm run lint`".  This would block anyone from merging in code that doesnt solve the lint rules.  We can also review when we meet next

**Comment by yamori** [comment]
resolves #3

**Review by zerske — APPROVED** [review]
Looks good! Definitely will have some questions about how this is fired (webhook, integration?) by GitHub and how you choose what to put in the "jobs" section.

**Comment by yamori** [comment]
> Looks good! Definitely will have some questions about how this is fired (webhook, integration?) by GitHub and how you choose what to put in the "jobs" section.

Cool, we can start with this on the Wed chat

**Pull request merged**
